// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

import java.util.ArrayList;

/** Record containing account details. */
public final class Account {


    /*package*/ final String mId;

    /*package*/ final String mCurrencyType;

    /*package*/ final String mCurrencyCode;

    /*package*/ final String mNetwork;

    /*package*/ final String mType;

    /*package*/ final String mCustodyType;

    /*package*/ final java.math.BigDecimal mBalance;

    /*package*/ final java.math.BigDecimal mLedgerBalance;

    /*package*/ final java.math.BigDecimal mAvailableBalance;

    /*package*/ final java.math.BigDecimal mOverdraftLimit;

    /*package*/ final boolean mHasNominatedAccount;

    /*package*/ final AccountCryptoProperties mCryptoProperties;

    /*package*/ final AccountFiatProperties mFiatProperties;

    /*package*/ final ArrayList<Card> mCards;

    public Account(
            String id,
            String currencyType,
            String currencyCode,
            String network,
            String type,
            String custodyType,
            java.math.BigDecimal balance,
            java.math.BigDecimal ledgerBalance,
            java.math.BigDecimal availableBalance,
            java.math.BigDecimal overdraftLimit,
            boolean hasNominatedAccount,
            AccountCryptoProperties cryptoProperties,
            AccountFiatProperties fiatProperties,
            ArrayList<Card> cards) {
        this.mId = id;
        this.mCurrencyType = currencyType;
        this.mCurrencyCode = currencyCode;
        this.mNetwork = network;
        this.mType = type;
        this.mCustodyType = custodyType;
        this.mBalance = balance;
        this.mLedgerBalance = ledgerBalance;
        this.mAvailableBalance = availableBalance;
        this.mOverdraftLimit = overdraftLimit;
        this.mHasNominatedAccount = hasNominatedAccount;
        this.mCryptoProperties = cryptoProperties;
        this.mFiatProperties = fiatProperties;
        this.mCards = cards;
    }

    /** Unique account identifier. */
    public String getId() {
        return mId;
    }

    /**
     * Account currency type.
     * @see CurrencyType
     */
    public String getCurrencyType() {
        return mCurrencyType;
    }

    /**
     * Account currency code.
     * @see CurrencyCode
     */
    public String getCurrencyCode() {
        return mCurrencyCode;
    }

    /**
     * Account network type.
     * @see NetworkType
     */
    public String getNetwork() {
        return mNetwork;
    }

    /**
     * Account type.
     * @see AccountType
     */
    public String getType() {
        return mType;
    }

    /**
     * Custody type.
     * @see CustodyType
     */
    public String getCustodyType() {
        return mCustodyType;
    }

    /** Account balance. */
    public java.math.BigDecimal getBalance() {
        return mBalance;
    }

    /** Account ledger balance. */
    public java.math.BigDecimal getLedgerBalance() {
        return mLedgerBalance;
    }

    /** Account available balance, i.e. ledger balance minus pending transactions. */
    public java.math.BigDecimal getAvailableBalance() {
        return mAvailableBalance;
    }

    /** Overdraft limit. */
    public java.math.BigDecimal getOverdraftLimit() {
        return mOverdraftLimit;
    }

    /** Account has associated nominated account. */
    public boolean getHasNominatedAccount() {
        return mHasNominatedAccount;
    }

    /** Account crypto properties if account is a crypto account, otherwise null. */
    public AccountCryptoProperties getCryptoProperties() {
        return mCryptoProperties;
    }

    /** Account fiat properties if account is a fiat account, otherwise null. */
    public AccountFiatProperties getFiatProperties() {
        return mFiatProperties;
    }

    /** Cards associated with this account. */
    public ArrayList<Card> getCards() {
        return mCards;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Account)) {
            return false;
        }
        Account other = (Account) obj;
        return this.mId.equals(other.mId) &&
                this.mCurrencyType.equals(other.mCurrencyType) &&
                this.mCurrencyCode.equals(other.mCurrencyCode) &&
                this.mNetwork.equals(other.mNetwork) &&
                this.mType.equals(other.mType) &&
                this.mCustodyType.equals(other.mCustodyType) &&
                this.mBalance.equals(other.mBalance) &&
                this.mLedgerBalance.equals(other.mLedgerBalance) &&
                this.mAvailableBalance.equals(other.mAvailableBalance) &&
                this.mOverdraftLimit.equals(other.mOverdraftLimit) &&
                this.mHasNominatedAccount == other.mHasNominatedAccount &&
                ((this.mCryptoProperties == null && other.mCryptoProperties == null) || (this.mCryptoProperties != null && this.mCryptoProperties.equals(other.mCryptoProperties))) &&
                ((this.mFiatProperties == null && other.mFiatProperties == null) || (this.mFiatProperties != null && this.mFiatProperties.equals(other.mFiatProperties))) &&
                this.mCards.equals(other.mCards);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mId.hashCode();
        hashCode = hashCode * 31 + mCurrencyType.hashCode();
        hashCode = hashCode * 31 + mCurrencyCode.hashCode();
        hashCode = hashCode * 31 + mNetwork.hashCode();
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + mCustodyType.hashCode();
        hashCode = hashCode * 31 + (mBalance.hashCode());
        hashCode = hashCode * 31 + (mLedgerBalance.hashCode());
        hashCode = hashCode * 31 + (mAvailableBalance.hashCode());
        hashCode = hashCode * 31 + (mOverdraftLimit.hashCode());
        hashCode = hashCode * 31 + (mHasNominatedAccount ? 1 : 0);
        hashCode = hashCode * 31 + (mCryptoProperties == null ? 0 : mCryptoProperties.hashCode());
        hashCode = hashCode * 31 + (mFiatProperties == null ? 0 : mFiatProperties.hashCode());
        hashCode = hashCode * 31 + mCards.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "Account{" +
                "mId=" + mId +
                "," + "mCurrencyType=" + mCurrencyType +
                "," + "mCurrencyCode=" + mCurrencyCode +
                "," + "mNetwork=" + mNetwork +
                "," + "mType=" + mType +
                "," + "mCustodyType=" + mCustodyType +
                "," + "mBalance=" + mBalance +
                "," + "mLedgerBalance=" + mLedgerBalance +
                "," + "mAvailableBalance=" + mAvailableBalance +
                "," + "mOverdraftLimit=" + mOverdraftLimit +
                "," + "mHasNominatedAccount=" + mHasNominatedAccount +
                "," + "mCryptoProperties=" + mCryptoProperties +
                "," + "mFiatProperties=" + mFiatProperties +
                "," + "mCards=" + mCards +
        "}";
    }

}
