// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

public interface AccountCallback {
    public void onError(Exception e);

    public void onSuccess(Account account);
}
