// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

/** Account type. Only relevant for Bitcoin accounts. All other accounts are STANDARD account type. */
public final class AccountType {

    public static final String STANDARD = "STANDARD";

    public static final String COMPATIBILITY = "COMPATIBILITY";

    public static final String SEGWIT = "SEGWIT";


    public AccountType(
            ) {
    }

    @Override
    public String toString() {
        return "AccountType{" +
        "}";
    }

}
