// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

/** Callback interface used to listen for account data changes in {@link  User User} class. */
public interface AccountDataListener {
    public void onDataChange(ArrayList<AccountDataSnapshot> snapshots);

    static final class CppProxy implements AccountDataListener
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onDataChange(ArrayList<AccountDataSnapshot> snapshots)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onDataChange(this.nativeRef, snapshots);
        }
        private native void native_onDataChange(long _nativeRef, ArrayList<AccountDataSnapshot> snapshots);
    }
}
