// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class Account {


    /*package*/ final String mId;

    /*package*/ final String mCurrencyType;

    /*package*/ final String mCurrencyCode;

    /*package*/ final String mNetwork;

    /*package*/ final String mType;

    /*package*/ final String mBalance;

    /*package*/ final boolean mHasNominatedAccount;

    /*package*/ final AccountCryptoProperties mCryptoProperties;

    /*package*/ final AccountFiatProperties mFiatProperties;

    public Account(
            String id,
            String currencyType,
            String currencyCode,
            String network,
            String type,
            String balance,
            boolean hasNominatedAccount,
            AccountCryptoProperties cryptoProperties,
            AccountFiatProperties fiatProperties) {
        this.mId = id;
        this.mCurrencyType = currencyType;
        this.mCurrencyCode = currencyCode;
        this.mNetwork = network;
        this.mType = type;
        this.mBalance = balance;
        this.mHasNominatedAccount = hasNominatedAccount;
        this.mCryptoProperties = cryptoProperties;
        this.mFiatProperties = fiatProperties;
    }

    public String getId() {
        return mId;
    }

    public String getCurrencyType() {
        return mCurrencyType;
    }

    public String getCurrencyCode() {
        return mCurrencyCode;
    }

    public String getNetwork() {
        return mNetwork;
    }

    public String getType() {
        return mType;
    }

    public String getBalance() {
        return mBalance;
    }

    public boolean getHasNominatedAccount() {
        return mHasNominatedAccount;
    }

    public AccountCryptoProperties getCryptoProperties() {
        return mCryptoProperties;
    }

    public AccountFiatProperties getFiatProperties() {
        return mFiatProperties;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Account)) {
            return false;
        }
        Account other = (Account) obj;
        return this.mId.equals(other.mId) &&
                this.mCurrencyType.equals(other.mCurrencyType) &&
                this.mCurrencyCode.equals(other.mCurrencyCode) &&
                this.mNetwork.equals(other.mNetwork) &&
                this.mType.equals(other.mType) &&
                this.mBalance.equals(other.mBalance) &&
                this.mHasNominatedAccount == other.mHasNominatedAccount &&
                ((this.mCryptoProperties == null && other.mCryptoProperties == null) || (this.mCryptoProperties != null && this.mCryptoProperties.equals(other.mCryptoProperties))) &&
                ((this.mFiatProperties == null && other.mFiatProperties == null) || (this.mFiatProperties != null && this.mFiatProperties.equals(other.mFiatProperties)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mId.hashCode();
        hashCode = hashCode * 31 + mCurrencyType.hashCode();
        hashCode = hashCode * 31 + mCurrencyCode.hashCode();
        hashCode = hashCode * 31 + mNetwork.hashCode();
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + mBalance.hashCode();
        hashCode = hashCode * 31 + (mHasNominatedAccount ? 1 : 0);
        hashCode = hashCode * 31 + (mCryptoProperties == null ? 0 : mCryptoProperties.hashCode());
        hashCode = hashCode * 31 + (mFiatProperties == null ? 0 : mFiatProperties.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "Account{" +
                "mId=" + mId +
                "," + "mCurrencyType=" + mCurrencyType +
                "," + "mCurrencyCode=" + mCurrencyCode +
                "," + "mNetwork=" + mNetwork +
                "," + "mType=" + mType +
                "," + "mBalance=" + mBalance +
                "," + "mHasNominatedAccount=" + mHasNominatedAccount +
                "," + "mCryptoProperties=" + mCryptoProperties +
                "," + "mFiatProperties=" + mFiatProperties +
        "}";
    }

}
