// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class Account {


    /*package*/ final String mId;

    /*package*/ final String mPath;

    /*package*/ final String mSymbol;

    /*package*/ final String mCoin;

    /*package*/ final String mAddress;

    /*package*/ final String mBalance;

    /*package*/ final Long mNonce;

    /*package*/ final NetworkType mNetwork;

    /*package*/ final AccountType mType;

    /*package*/ final String mUtxoPool;

    /*package*/ final byte mVersion;

    public Account(
            String id,
            String path,
            String symbol,
            String coin,
            String address,
            String balance,
            Long nonce,
            NetworkType network,
            AccountType type,
            String utxoPool,
            byte version) {
        this.mId = id;
        this.mPath = path;
        this.mSymbol = symbol;
        this.mCoin = coin;
        this.mAddress = address;
        this.mBalance = balance;
        this.mNonce = nonce;
        this.mNetwork = network;
        this.mType = type;
        this.mUtxoPool = utxoPool;
        this.mVersion = version;
    }

    public String getId() {
        return mId;
    }

    public String getPath() {
        return mPath;
    }

    public String getSymbol() {
        return mSymbol;
    }

    public String getCoin() {
        return mCoin;
    }

    public String getAddress() {
        return mAddress;
    }

    public String getBalance() {
        return mBalance;
    }

    public Long getNonce() {
        return mNonce;
    }

    public NetworkType getNetwork() {
        return mNetwork;
    }

    public AccountType getType() {
        return mType;
    }

    public String getUtxoPool() {
        return mUtxoPool;
    }

    public byte getVersion() {
        return mVersion;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Account)) {
            return false;
        }
        Account other = (Account) obj;
        return this.mId.equals(other.mId) &&
                this.mPath.equals(other.mPath) &&
                this.mSymbol.equals(other.mSymbol) &&
                this.mCoin.equals(other.mCoin) &&
                this.mAddress.equals(other.mAddress) &&
                this.mBalance.equals(other.mBalance) &&
                ((this.mNonce == null && other.mNonce == null) || (this.mNonce != null && this.mNonce.equals(other.mNonce))) &&
                this.mNetwork == other.mNetwork &&
                this.mType == other.mType &&
                ((this.mUtxoPool == null && other.mUtxoPool == null) || (this.mUtxoPool != null && this.mUtxoPool.equals(other.mUtxoPool))) &&
                this.mVersion == other.mVersion;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mId.hashCode();
        hashCode = hashCode * 31 + mPath.hashCode();
        hashCode = hashCode * 31 + mSymbol.hashCode();
        hashCode = hashCode * 31 + mCoin.hashCode();
        hashCode = hashCode * 31 + mAddress.hashCode();
        hashCode = hashCode * 31 + mBalance.hashCode();
        hashCode = hashCode * 31 + (mNonce == null ? 0 : mNonce.hashCode());
        hashCode = hashCode * 31 + mNetwork.hashCode();
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + (mUtxoPool == null ? 0 : mUtxoPool.hashCode());
        hashCode = hashCode * 31 + mVersion;
        return hashCode;
    }

    @Override
    public String toString() {
        return "Account{" +
                "mId=" + mId +
                "," + "mPath=" + mPath +
                "," + "mSymbol=" + mSymbol +
                "," + "mCoin=" + mCoin +
                "," + "mAddress=" + mAddress +
                "," + "mBalance=" + mBalance +
                "," + "mNonce=" + mNonce +
                "," + "mNetwork=" + mNetwork +
                "," + "mType=" + mType +
                "," + "mUtxoPool=" + mUtxoPool +
                "," + "mVersion=" + mVersion +
        "}";
    }

}
