// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class AccountFiatProperties {


    /*package*/ final String mAccountNumber;

    /*package*/ final String mSortCode;

    /*package*/ final String mBic;

    /*package*/ final String mIban;

    /*package*/ final String mCustomerName;

    public AccountFiatProperties(
            String accountNumber,
            String sortCode,
            String bic,
            String iban,
            String customerName) {
        this.mAccountNumber = accountNumber;
        this.mSortCode = sortCode;
        this.mBic = bic;
        this.mIban = iban;
        this.mCustomerName = customerName;
    }

    public String getAccountNumber() {
        return mAccountNumber;
    }

    public String getSortCode() {
        return mSortCode;
    }

    public String getBic() {
        return mBic;
    }

    public String getIban() {
        return mIban;
    }

    public String getCustomerName() {
        return mCustomerName;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof AccountFiatProperties)) {
            return false;
        }
        AccountFiatProperties other = (AccountFiatProperties) obj;
        return ((this.mAccountNumber == null && other.mAccountNumber == null) || (this.mAccountNumber != null && this.mAccountNumber.equals(other.mAccountNumber))) &&
                ((this.mSortCode == null && other.mSortCode == null) || (this.mSortCode != null && this.mSortCode.equals(other.mSortCode))) &&
                ((this.mBic == null && other.mBic == null) || (this.mBic != null && this.mBic.equals(other.mBic))) &&
                ((this.mIban == null && other.mIban == null) || (this.mIban != null && this.mIban.equals(other.mIban))) &&
                ((this.mCustomerName == null && other.mCustomerName == null) || (this.mCustomerName != null && this.mCustomerName.equals(other.mCustomerName)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + (mAccountNumber == null ? 0 : mAccountNumber.hashCode());
        hashCode = hashCode * 31 + (mSortCode == null ? 0 : mSortCode.hashCode());
        hashCode = hashCode * 31 + (mBic == null ? 0 : mBic.hashCode());
        hashCode = hashCode * 31 + (mIban == null ? 0 : mIban.hashCode());
        hashCode = hashCode * 31 + (mCustomerName == null ? 0 : mCustomerName.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "AccountFiatProperties{" +
                "mAccountNumber=" + mAccountNumber +
                "," + "mSortCode=" + mSortCode +
                "," + "mBic=" + mBic +
                "," + "mIban=" + mIban +
                "," + "mCustomerName=" + mCustomerName +
        "}";
    }

}
