// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

/** Record describing user address details */
public final class Address {


    /*package*/ final String mHouseNumber;

    /*package*/ final String mAddressLine1;

    /*package*/ final String mAddressLine2;

    /*package*/ final String mCountry;

    /*package*/ final String mPostCode;

    /*package*/ final String mPostTown;

    public Address(
            String houseNumber,
            String addressLine1,
            String addressLine2,
            String country,
            String postCode,
            String postTown) {
        this.mHouseNumber = houseNumber;
        this.mAddressLine1 = addressLine1;
        this.mAddressLine2 = addressLine2;
        this.mCountry = country;
        this.mPostCode = postCode;
        this.mPostTown = postTown;
    }

    /** House number. */
    public String getHouseNumber() {
        return mHouseNumber;
    }

    /** First line of address. */
    public String getAddressLine1() {
        return mAddressLine1;
    }

    /** Second line of address or null. */
    public String getAddressLine2() {
        return mAddressLine2;
    }

    /** Country code in ISO 3166-1 Alpha-2 format, e.g. 'GB'. */
    public String getCountry() {
        return mCountry;
    }

    /** Post code. */
    public String getPostCode() {
        return mPostCode;
    }

    /** Post town */
    public String getPostTown() {
        return mPostTown;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Address)) {
            return false;
        }
        Address other = (Address) obj;
        return this.mHouseNumber.equals(other.mHouseNumber) &&
                this.mAddressLine1.equals(other.mAddressLine1) &&
                ((this.mAddressLine2 == null && other.mAddressLine2 == null) || (this.mAddressLine2 != null && this.mAddressLine2.equals(other.mAddressLine2))) &&
                this.mCountry.equals(other.mCountry) &&
                this.mPostCode.equals(other.mPostCode) &&
                this.mPostTown.equals(other.mPostTown);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mHouseNumber.hashCode();
        hashCode = hashCode * 31 + mAddressLine1.hashCode();
        hashCode = hashCode * 31 + (mAddressLine2 == null ? 0 : mAddressLine2.hashCode());
        hashCode = hashCode * 31 + mCountry.hashCode();
        hashCode = hashCode * 31 + mPostCode.hashCode();
        hashCode = hashCode * 31 + mPostTown.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "Address{" +
                "mHouseNumber=" + mHouseNumber +
                "," + "mAddressLine1=" + mAddressLine1 +
                "," + "mAddressLine2=" + mAddressLine2 +
                "," + "mCountry=" + mCountry +
                "," + "mPostCode=" + mPostCode +
                "," + "mPostTown=" + mPostTown +
        "}";
    }

}
