// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

public interface AuthCallback {
    public void onError(Exception e);

    public void onSuccess(User user);
}
