// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Card status, for example 'ACTIVE'. */
public final class CardStatus {

    public static final String CREATED = "CREATED";

    public static final String ACTIVE = "ACTIVE";

    public static final String BLOCKED = "BLOCKED";

    public static final String SUSPENDED = "SUSPENDED";

    public static final String FROZEN = "FROZEN";

    public static final String EXPIRED = "EXPIRED";

    public static final String CANCELLED = "CANCELLED";


    public CardStatus(
            ) {
    }

    @Override
    public String toString() {
        return "CardStatus{" +
        "}";
    }

}
