// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Card type, 'VIRTUAL' or 'PHYSICAL'. */
public final class CardType {

    public static final String VIRTUAL = "VIRTUAL";

    public static final String PHYSICAL = "PHYSICAL";


    public CardType(
            ) {
    }

    @Override
    public String toString() {
        return "CardType{" +
        "}";
    }

}
