// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in {@link  Wallet Wallet} class. */
public interface ComposeTransactionCallback {
    public void onError(Exception e);

    public void onSuccess(ComposedTransaction composedTransaction);
}
