// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in {@link  Wallet Wallet} class. */
public interface ComposeExchangeCallback {
    public void onError(Exception e);

    public void onSuccess(ComposedExchange composedExchange);
}
