// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class ComposedTransaction {


    /*package*/ final String mSignedTransaction;

    /*package*/ final Account mAccount;

    /*package*/ final String mDestination;

    /*package*/ final String mAmount;

    /*package*/ final String mData;

    /*package*/ final String mFee;

    public ComposedTransaction(
            String signedTransaction,
            Account account,
            String destination,
            String amount,
            String data,
            String fee) {
        this.mSignedTransaction = signedTransaction;
        this.mAccount = account;
        this.mDestination = destination;
        this.mAmount = amount;
        this.mData = data;
        this.mFee = fee;
    }

    public String getSignedTransaction() {
        return mSignedTransaction;
    }

    public Account getAccount() {
        return mAccount;
    }

    public String getDestination() {
        return mDestination;
    }

    public String getAmount() {
        return mAmount;
    }

    public String getData() {
        return mData;
    }

    public String getFee() {
        return mFee;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof ComposedTransaction)) {
            return false;
        }
        ComposedTransaction other = (ComposedTransaction) obj;
        return this.mSignedTransaction.equals(other.mSignedTransaction) &&
                this.mAccount.equals(other.mAccount) &&
                ((this.mDestination == null && other.mDestination == null) || (this.mDestination != null && this.mDestination.equals(other.mDestination))) &&
                ((this.mAmount == null && other.mAmount == null) || (this.mAmount != null && this.mAmount.equals(other.mAmount))) &&
                ((this.mData == null && other.mData == null) || (this.mData != null && this.mData.equals(other.mData))) &&
                this.mFee.equals(other.mFee);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mSignedTransaction.hashCode();
        hashCode = hashCode * 31 + mAccount.hashCode();
        hashCode = hashCode * 31 + (mDestination == null ? 0 : mDestination.hashCode());
        hashCode = hashCode * 31 + (mAmount == null ? 0 : mAmount.hashCode());
        hashCode = hashCode * 31 + (mData == null ? 0 : mData.hashCode());
        hashCode = hashCode * 31 + mFee.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "ComposedTransaction{" +
                "mSignedTransaction=" + mSignedTransaction +
                "," + "mAccount=" + mAccount +
                "," + "mDestination=" + mDestination +
                "," + "mAmount=" + mAmount +
                "," + "mData=" + mData +
                "," + "mFee=" + mFee +
        "}";
    }

}
