// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class CryptoProperties {


    /*package*/ final String mAddress;

    /*package*/ final String mPath;

    /*package*/ final Long mNonce;

    /*package*/ final String mUtxoPool;

    /*package*/ final byte mVersion;

    public CryptoProperties(
            String address,
            String path,
            Long nonce,
            String utxoPool,
            byte version) {
        this.mAddress = address;
        this.mPath = path;
        this.mNonce = nonce;
        this.mUtxoPool = utxoPool;
        this.mVersion = version;
    }

    public String getAddress() {
        return mAddress;
    }

    public String getPath() {
        return mPath;
    }

    public Long getNonce() {
        return mNonce;
    }

    public String getUtxoPool() {
        return mUtxoPool;
    }

    public byte getVersion() {
        return mVersion;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof CryptoProperties)) {
            return false;
        }
        CryptoProperties other = (CryptoProperties) obj;
        return this.mAddress.equals(other.mAddress) &&
                this.mPath.equals(other.mPath) &&
                ((this.mNonce == null && other.mNonce == null) || (this.mNonce != null && this.mNonce.equals(other.mNonce))) &&
                ((this.mUtxoPool == null && other.mUtxoPool == null) || (this.mUtxoPool != null && this.mUtxoPool.equals(other.mUtxoPool))) &&
                this.mVersion == other.mVersion;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mAddress.hashCode();
        hashCode = hashCode * 31 + mPath.hashCode();
        hashCode = hashCode * 31 + (mNonce == null ? 0 : mNonce.hashCode());
        hashCode = hashCode * 31 + (mUtxoPool == null ? 0 : mUtxoPool.hashCode());
        hashCode = hashCode * 31 + mVersion;
        return hashCode;
    }

    @Override
    public String toString() {
        return "CryptoProperties{" +
                "mAddress=" + mAddress +
                "," + "mPath=" + mPath +
                "," + "mNonce=" + mNonce +
                "," + "mUtxoPool=" + mUtxoPool +
                "," + "mVersion=" + mVersion +
        "}";
    }

}
