// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

/** Currency code, such as 'GBP', 'BTC' or 'ETH'. */
public final class CurrencyCode {

    public static final String GBP = "GBP";

    public static final String USD = "USD";

    public static final String ETH = "ETH";

    public static final String BTC = "BTC";


    public CurrencyCode(
            ) {
    }

    @Override
    public String toString() {
        return "CurrencyCode{" +
        "}";
    }

}
