// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class CurrencyType {

    public static final String FIAT = "FIAT";

    public static final String CRYPTO = "CRYPTO";


    public CurrencyType(
            ) {
    }

    @Override
    public String toString() {
        return "CurrencyType{" +
        "}";
    }

}
