// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Currency code, for example 'GBP'. */
public final class CurrencyCode {

    public static final String GBP = "GBP";

    public static final String ETH = "ETH";

    public static final String BTC = "BTC";

    public static final String BSV = "BSV";


    public CurrencyCode(
            ) {
    }

    @Override
    public String toString() {
        return "CurrencyCode{" +
        "}";
    }

}
