// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Custody order type, 'DEPOSIT' or 'WITHDRAW'. */
public final class CustodyOrderType {

    public static final String DEPOSIT = "DEPOSIT";

    public static final String WITHDRAW = "WITHDRAW";


    public CustodyOrderType(
            ) {
    }

    @Override
    public String toString() {
        return "CustodyOrderType{" +
        "}";
    }

}
