// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Exchange side, 'BUY' or 'SELL'. */
public final class ExchangeSide {

    public static final String BUY = "BUY";

    public static final String SELL = "SELL";


    public ExchangeSide(
            ) {
    }

    @Override
    public String toString() {
        return "ExchangeSide{" +
        "}";
    }

}
