// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public enum ExchangeStatus {
    PENDING_DEPOSIT,
    PENDING_WITHDRAW,
    CONFIRMED,
    FAILED,
    RESUBMITTED,
    CANCELLED,
    PAUSED,
    ;
}
