// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/**
 * Exchange status, for example 'PENDING'.
 * <p>
 * Once exchange is submitted it has to be confirmed. Once exchange is confirmed its status will change from pending to confirmed.
 * <p>
 * See <a target="_top" href="https://developers.zumo.money/docs/guides/make-exchanges#exchange-statuses">Make Exchanges</a> guide for details.
 */
public final class ExchangeStatus {

    /** Outgoing transaction has been submitted. */
    public static final String PENDING = "PENDING";

    /** Outgoing transaction has been mined and return transaction has been initiated. */
    public static final String WITHDRAWING = "WITHDRAWING";

    /** Exchange was confirmed. */
    public static final String CONFIRMED = "CONFIRMED";

    /** Exchange has failed. */
    public static final String FAILED = "FAILED";


    public ExchangeStatus(
            ) {
    }

    @Override
    public String toString() {
        return "ExchangeStatus{" +
        "}";
    }

}
