// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

import java.util.HashMap;

public final class ExchangeSettings {


    /*package*/ final String mId;

    /*package*/ final HashMap<String, String> mDepositAddress;

    /*package*/ final String mDepositCurrency;

    /*package*/ final String mWithdrawCurrency;

    /*package*/ final String mMinExchangeAmount;

    /*package*/ final String mFeeRate;

    /*package*/ final String mDepositFeeRate;

    /*package*/ final String mWithdrawFee;

    /*package*/ final long mTimestamp;

    public ExchangeSettings(
            String id,
            HashMap<String, String> depositAddress,
            String depositCurrency,
            String withdrawCurrency,
            String minExchangeAmount,
            String feeRate,
            String depositFeeRate,
            String withdrawFee,
            long timestamp) {
        this.mId = id;
        this.mDepositAddress = depositAddress;
        this.mDepositCurrency = depositCurrency;
        this.mWithdrawCurrency = withdrawCurrency;
        this.mMinExchangeAmount = minExchangeAmount;
        this.mFeeRate = feeRate;
        this.mDepositFeeRate = depositFeeRate;
        this.mWithdrawFee = withdrawFee;
        this.mTimestamp = timestamp;
    }

    public String getId() {
        return mId;
    }

    public HashMap<String, String> getDepositAddress() {
        return mDepositAddress;
    }

    public String getDepositCurrency() {
        return mDepositCurrency;
    }

    public String getWithdrawCurrency() {
        return mWithdrawCurrency;
    }

    public String getMinExchangeAmount() {
        return mMinExchangeAmount;
    }

    public String getFeeRate() {
        return mFeeRate;
    }

    public String getDepositFeeRate() {
        return mDepositFeeRate;
    }

    public String getWithdrawFee() {
        return mWithdrawFee;
    }

    public long getTimestamp() {
        return mTimestamp;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof ExchangeSettings)) {
            return false;
        }
        ExchangeSettings other = (ExchangeSettings) obj;
        return this.mId.equals(other.mId) &&
                this.mDepositAddress.equals(other.mDepositAddress) &&
                this.mDepositCurrency.equals(other.mDepositCurrency) &&
                this.mWithdrawCurrency.equals(other.mWithdrawCurrency) &&
                this.mMinExchangeAmount.equals(other.mMinExchangeAmount) &&
                this.mFeeRate.equals(other.mFeeRate) &&
                this.mDepositFeeRate.equals(other.mDepositFeeRate) &&
                this.mWithdrawFee.equals(other.mWithdrawFee) &&
                this.mTimestamp == other.mTimestamp;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mId.hashCode();
        hashCode = hashCode * 31 + mDepositAddress.hashCode();
        hashCode = hashCode * 31 + mDepositCurrency.hashCode();
        hashCode = hashCode * 31 + mWithdrawCurrency.hashCode();
        hashCode = hashCode * 31 + mMinExchangeAmount.hashCode();
        hashCode = hashCode * 31 + mFeeRate.hashCode();
        hashCode = hashCode * 31 + mDepositFeeRate.hashCode();
        hashCode = hashCode * 31 + mWithdrawFee.hashCode();
        hashCode = hashCode * 31 + ((int) (mTimestamp ^ (mTimestamp >>> 32)));
        return hashCode;
    }

    @Override
    public String toString() {
        return "ExchangeSettings{" +
                "mId=" + mId +
                "," + "mDepositAddress=" + mDepositAddress +
                "," + "mDepositCurrency=" + mDepositCurrency +
                "," + "mWithdrawCurrency=" + mWithdrawCurrency +
                "," + "mMinExchangeAmount=" + mMinExchangeAmount +
                "," + "mFeeRate=" + mFeeRate +
                "," + "mDepositFeeRate=" + mDepositFeeRate +
                "," + "mWithdrawFee=" + mWithdrawFee +
                "," + "mTimestamp=" + mTimestamp +
        "}";
    }

}
