// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class FeeRates {


    /*package*/ final java.math.BigDecimal mSlow;

    /*package*/ final java.math.BigDecimal mAverage;

    /*package*/ final java.math.BigDecimal mFast;

    /*package*/ final float mSlowTime;

    /*package*/ final float mAverageTime;

    /*package*/ final float mFastTime;

    /*package*/ final String mSource;

    public FeeRates(
            java.math.BigDecimal slow,
            java.math.BigDecimal average,
            java.math.BigDecimal fast,
            float slowTime,
            float averageTime,
            float fastTime,
            String source) {
        this.mSlow = slow;
        this.mAverage = average;
        this.mFast = fast;
        this.mSlowTime = slowTime;
        this.mAverageTime = averageTime;
        this.mFastTime = fastTime;
        this.mSource = source;
    }

    public java.math.BigDecimal getSlow() {
        return mSlow;
    }

    public java.math.BigDecimal getAverage() {
        return mAverage;
    }

    public java.math.BigDecimal getFast() {
        return mFast;
    }

    public float getSlowTime() {
        return mSlowTime;
    }

    public float getAverageTime() {
        return mAverageTime;
    }

    public float getFastTime() {
        return mFastTime;
    }

    public String getSource() {
        return mSource;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof FeeRates)) {
            return false;
        }
        FeeRates other = (FeeRates) obj;
        return this.mSlow.equals(other.mSlow) &&
                this.mAverage.equals(other.mAverage) &&
                this.mFast.equals(other.mFast) &&
                this.mSlowTime == other.mSlowTime &&
                this.mAverageTime == other.mAverageTime &&
                this.mFastTime == other.mFastTime &&
                this.mSource.equals(other.mSource);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + (mSlow.hashCode());
        hashCode = hashCode * 31 + (mAverage.hashCode());
        hashCode = hashCode * 31 + (mFast.hashCode());
        hashCode = hashCode * 31 + Float.floatToIntBits(mSlowTime);
        hashCode = hashCode * 31 + Float.floatToIntBits(mAverageTime);
        hashCode = hashCode * 31 + Float.floatToIntBits(mFastTime);
        hashCode = hashCode * 31 + mSource.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "FeeRates{" +
                "mSlow=" + mSlow +
                "," + "mAverage=" + mAverage +
                "," + "mFast=" + mFast +
                "," + "mSlowTime=" + mSlowTime +
                "," + "mAverageTime=" + mAverageTime +
                "," + "mFastTime=" + mFastTime +
                "," + "mSource=" + mSource +
        "}";
    }

}
