// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

import java.util.ArrayList;
import java.util.HashMap;

/** Callback interface used by methods in @link ZumoKit class */
public interface HistoricalExchangeRatesCallback {
    public void onError(Exception e);

    public void onSuccess(HashMap<String, HashMap<String, HashMap<String, ArrayList<ExchangeRate>>>> historicalExchangeRates);
}
