// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

public final class HistoricalExchangeRatesInterval {

    public static final String HOUR = "hour";

    public static final String DAY = "day";

    public static final String WEEK = "week";

    public static final String MONTH = "month";

    public static final String QUARTER = "quarter";

    public static final String YEAR = "year";


    public HistoricalExchangeRatesInterval(
            ) {
    }

    @Override
    public String toString() {
        return "HistoricalExchangeRatesInterval{" +
        "}";
    }

}
