// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

package money.zumo.zumokit;

import java.util.HashMap;
import java.util.concurrent.atomic.AtomicBoolean;

public interface HttpImpl {
    public void request(String url, String method, HashMap<String, String> headers, String data, HttpCallback callback);

    static final class CppProxy implements HttpImpl
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void request(String url, String method, HashMap<String, String> headers, String data, HttpCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_request(this.nativeRef, url, method, headers, data, callback);
        }
        private native void native_request(long _nativeRef, String url, String method, HashMap<String, String> headers, String data, HttpCallback callback);
    }
}
