// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

/** Record containing Knowledge-Based Authentication (KBA) answer. */
public final class KbaAnswer {


    /*package*/ final String mType;

    /*package*/ final String mAnswer;

    public KbaAnswer(
            String type,
            String answer) {
        this.mType = type;
        this.mAnswer = answer;
    }

    /** KBA question type, e.g. "FIRST_PET_NAME". */
    public String getType() {
        return mType;
    }

    /** KBA answer, e.g. "Shurik". */
    public String getAnswer() {
        return mAnswer;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof KbaAnswer)) {
            return false;
        }
        KbaAnswer other = (KbaAnswer) obj;
        return this.mType.equals(other.mType) &&
                this.mAnswer.equals(other.mAnswer);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + mAnswer.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "KbaAnswer{" +
                "mType=" + mType +
                "," + "mAnswer=" + mAnswer +
        "}";
    }

}
