// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

/** Record containing Knowledge-Based Authentication (KBA) question */
public final class KbaQuestion {


    /*package*/ final String mType;

    /*package*/ final String mQuestion;

    public KbaQuestion(
            String type,
            String question) {
        this.mType = type;
        this.mQuestion = question;
    }

    /** KBA question type, e.g. "FIRST_PET_NAME" */
    public String getType() {
        return mType;
    }

    /** KBA question, e.g. "What was your first pet's name?" */
    public String getQuestion() {
        return mQuestion;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof KbaQuestion)) {
            return false;
        }
        KbaQuestion other = (KbaQuestion) obj;
        return this.mType.equals(other.mType) &&
                this.mQuestion.equals(other.mQuestion);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + mQuestion.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "KbaQuestion{" +
                "mType=" + mType +
                "," + "mQuestion=" + mQuestion +
        "}";
    }

}
