// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

import java.util.concurrent.atomic.AtomicBoolean;

/** Log interface used to listen for debug information in {@link  ZumoKit ZumoKit} class. */
public interface LogListener {
    public void onLog(String message);

    static final class CppProxy implements LogListener
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onLog(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onLog(this.nativeRef, message);
        }
        private native void native_onLog(long _nativeRef, String message);
    }
}
