// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

public interface MnemonicCallback {
    public void onError(Exception e);

    public void onSuccess(String mnemonic);
}
