// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Network type, such as 'MAINNET', 'TESTNET' or 'RINKEBY'. */
public final class NetworkType {

    public static final String MAINNET = "MAINNET";

    public static final String TESTNET = "TESTNET";

    public static final String ROPSTEN = "ROPSTEN";

    public static final String RINKEBY = "RINKEBY";

    public static final String GOERLI = "GOERLI";

    public static final String KOVAN = "KOVAN";


    public NetworkType(
            ) {
    }

    @Override
    public String toString() {
        return "NetworkType{" +
        "}";
    }

}
