// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public enum NetworkType {
    MAINNET,
    TESTNET,
    ROPSTEN,
    RINKEBY,
    GOERLI,
    KOVAN,
    ;
}
