// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

/** Record containing Zumo exchange rate quote used in making exchanges. */
public final class Quote {


    /*package*/ final String mId;

    /*package*/ final int mTtl;

    /*package*/ final String mCreatedAt;

    /*package*/ final String mExpiresAt;

    /*package*/ final String mDebitCurrency;

    /*package*/ final String mCreditCurrency;

    /*package*/ final java.math.BigDecimal mPrice;

    /*package*/ final java.math.BigDecimal mFeeRate;

    /*package*/ final java.math.BigDecimal mDebitAmount;

    /*package*/ final java.math.BigDecimal mFeeAmount;

    /*package*/ final java.math.BigDecimal mCreditAmount;

    public Quote(
            String id,
            int ttl,
            String createdAt,
            String expiresAt,
            String debitCurrency,
            String creditCurrency,
            java.math.BigDecimal price,
            java.math.BigDecimal feeRate,
            java.math.BigDecimal debitAmount,
            java.math.BigDecimal feeAmount,
            java.math.BigDecimal creditAmount) {
        this.mId = id;
        this.mTtl = ttl;
        this.mCreatedAt = createdAt;
        this.mExpiresAt = expiresAt;
        this.mDebitCurrency = debitCurrency;
        this.mCreditCurrency = creditCurrency;
        this.mPrice = price;
        this.mFeeRate = feeRate;
        this.mDebitAmount = debitAmount;
        this.mFeeAmount = feeAmount;
        this.mCreditAmount = creditAmount;
    }

    /** Identifier. */
    public String getId() {
        return mId;
    }

    /** Expiration in seconds at the time of quote creation, e.g. 60. */
    public int getTtl() {
        return mTtl;
    }

    /** Timestamp when quote was created, e.g.  "2022-10-13T12:39:59.056Z". */
    public String getCreatedAt() {
        return mCreatedAt;
    }

    /** Timestamp representing expiration time of this quote, e.g. "2022-10-13T12:40:58.871Z". */
    public String getExpiresAt() {
        return mExpiresAt;
    }

    /**
     * Debit currency.
     * @see CurrencyCode
     */
    public String getDebitCurrency() {
        return mDebitCurrency;
    }

    /**
     * Credit currency.
     * @see CurrencyCode
     */
    public String getCreditCurrency() {
        return mCreditCurrency;
    }

    /** Value of 1 unit of debit currency in credit currency. */
    public java.math.BigDecimal getPrice() {
        return mPrice;
    }

    /** Fee rate in points of a percentage, e.g. "0.1" representing 0.1% */
    public java.math.BigDecimal getFeeRate() {
        return mFeeRate;
    }

    /** Amount to be debited from debit account. */
    public java.math.BigDecimal getDebitAmount() {
        return mDebitAmount;
    }

    /** Amount that will be paid in fees. */
    public java.math.BigDecimal getFeeAmount() {
        return mFeeAmount;
    }

    /** Amount to be credited to credit account. */
    public java.math.BigDecimal getCreditAmount() {
        return mCreditAmount;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Quote)) {
            return false;
        }
        Quote other = (Quote) obj;
        return this.mId.equals(other.mId) &&
                this.mTtl == other.mTtl &&
                this.mCreatedAt.equals(other.mCreatedAt) &&
                this.mExpiresAt.equals(other.mExpiresAt) &&
                this.mDebitCurrency.equals(other.mDebitCurrency) &&
                this.mCreditCurrency.equals(other.mCreditCurrency) &&
                this.mPrice.equals(other.mPrice) &&
                this.mFeeRate.equals(other.mFeeRate) &&
                this.mDebitAmount.equals(other.mDebitAmount) &&
                this.mFeeAmount.equals(other.mFeeAmount) &&
                this.mCreditAmount.equals(other.mCreditAmount);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mId.hashCode();
        hashCode = hashCode * 31 + mTtl;
        hashCode = hashCode * 31 + mCreatedAt.hashCode();
        hashCode = hashCode * 31 + mExpiresAt.hashCode();
        hashCode = hashCode * 31 + mDebitCurrency.hashCode();
        hashCode = hashCode * 31 + mCreditCurrency.hashCode();
        hashCode = hashCode * 31 + (mPrice.hashCode());
        hashCode = hashCode * 31 + (mFeeRate.hashCode());
        hashCode = hashCode * 31 + (mDebitAmount.hashCode());
        hashCode = hashCode * 31 + (mFeeAmount.hashCode());
        hashCode = hashCode * 31 + (mCreditAmount.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "Quote{" +
                "mId=" + mId +
                "," + "mTtl=" + mTtl +
                "," + "mCreatedAt=" + mCreatedAt +
                "," + "mExpiresAt=" + mExpiresAt +
                "," + "mDebitCurrency=" + mDebitCurrency +
                "," + "mCreditCurrency=" + mCreditCurrency +
                "," + "mPrice=" + mPrice +
                "," + "mFeeRate=" + mFeeRate +
                "," + "mDebitAmount=" + mDebitAmount +
                "," + "mFeeAmount=" + mFeeAmount +
                "," + "mCreditAmount=" + mCreditAmount +
        "}";
    }

}
