// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in {@link  User User} class. */
public interface QuoteCallback {
    public void onError(Exception e);

    public void onSuccess(Quote quote);
}
