// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

import java.util.ArrayList;
import java.util.HashMap;

public final class State {


    /*package*/ final ArrayList<Account> mAccounts;

    /*package*/ final ArrayList<Transaction> mTransactions;

    /*package*/ final ArrayList<Exchange> mExchanges;

    /*package*/ final String mToken;

    /*package*/ final String mActiveUserId;

    /*package*/ final HashMap<String, HashMap<String, ExchangeRate>> mExchangeRates;

    /*package*/ final HashMap<String, HashMap<String, ExchangeSettings>> mExchangeSettings;

    /*package*/ final HashMap<String, FeeRates> mFeeRates;

    /*package*/ final ArrayList<String> mModulrCustomerOnNetworks;

    public State(
            ArrayList<Account> accounts,
            ArrayList<Transaction> transactions,
            ArrayList<Exchange> exchanges,
            String token,
            String activeUserId,
            HashMap<String, HashMap<String, ExchangeRate>> exchangeRates,
            HashMap<String, HashMap<String, ExchangeSettings>> exchangeSettings,
            HashMap<String, FeeRates> feeRates,
            ArrayList<String> modulrCustomerOnNetworks) {
        this.mAccounts = accounts;
        this.mTransactions = transactions;
        this.mExchanges = exchanges;
        this.mToken = token;
        this.mActiveUserId = activeUserId;
        this.mExchangeRates = exchangeRates;
        this.mExchangeSettings = exchangeSettings;
        this.mFeeRates = feeRates;
        this.mModulrCustomerOnNetworks = modulrCustomerOnNetworks;
    }

    public ArrayList<Account> getAccounts() {
        return mAccounts;
    }

    public ArrayList<Transaction> getTransactions() {
        return mTransactions;
    }

    public ArrayList<Exchange> getExchanges() {
        return mExchanges;
    }

    public String getToken() {
        return mToken;
    }

    public String getActiveUserId() {
        return mActiveUserId;
    }

    public HashMap<String, HashMap<String, ExchangeRate>> getExchangeRates() {
        return mExchangeRates;
    }

    public HashMap<String, HashMap<String, ExchangeSettings>> getExchangeSettings() {
        return mExchangeSettings;
    }

    public HashMap<String, FeeRates> getFeeRates() {
        return mFeeRates;
    }

    public ArrayList<String> getModulrCustomerOnNetworks() {
        return mModulrCustomerOnNetworks;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof State)) {
            return false;
        }
        State other = (State) obj;
        return this.mAccounts.equals(other.mAccounts) &&
                this.mTransactions.equals(other.mTransactions) &&
                this.mExchanges.equals(other.mExchanges) &&
                this.mToken.equals(other.mToken) &&
                ((this.mActiveUserId == null && other.mActiveUserId == null) || (this.mActiveUserId != null && this.mActiveUserId.equals(other.mActiveUserId))) &&
                this.mExchangeRates.equals(other.mExchangeRates) &&
                this.mExchangeSettings.equals(other.mExchangeSettings) &&
                this.mFeeRates.equals(other.mFeeRates) &&
                this.mModulrCustomerOnNetworks.equals(other.mModulrCustomerOnNetworks);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mAccounts.hashCode();
        hashCode = hashCode * 31 + mTransactions.hashCode();
        hashCode = hashCode * 31 + mExchanges.hashCode();
        hashCode = hashCode * 31 + mToken.hashCode();
        hashCode = hashCode * 31 + (mActiveUserId == null ? 0 : mActiveUserId.hashCode());
        hashCode = hashCode * 31 + mExchangeRates.hashCode();
        hashCode = hashCode * 31 + mExchangeSettings.hashCode();
        hashCode = hashCode * 31 + mFeeRates.hashCode();
        hashCode = hashCode * 31 + mModulrCustomerOnNetworks.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "State{" +
                "mAccounts=" + mAccounts +
                "," + "mTransactions=" + mTransactions +
                "," + "mExchanges=" + mExchanges +
                "," + "mToken=" + mToken +
                "," + "mActiveUserId=" + mActiveUserId +
                "," + "mExchangeRates=" + mExchangeRates +
                "," + "mExchangeSettings=" + mExchangeSettings +
                "," + "mFeeRates=" + mFeeRates +
                "," + "mModulrCustomerOnNetworks=" + mModulrCustomerOnNetworks +
        "}";
    }

}
