// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

import java.util.ArrayList;
import java.util.HashMap;

public final class State {


    /*package*/ final ArrayList<Account> mAccounts;

    /*package*/ final ArrayList<Transaction> mTransactions;

    /*package*/ final String mToken;

    /*package*/ final String mActiveUserId;

    /*package*/ final String mExchangeRates;

    /*package*/ final TxServiceConnection mTxServiceConnection;

    /*package*/ final HashMap<String, FeeRates> mFeeRates;

    /*package*/ final SyncStatus mSyncStatus;

    public State(
            ArrayList<Account> accounts,
            ArrayList<Transaction> transactions,
            String token,
            String activeUserId,
            String exchangeRates,
            TxServiceConnection txServiceConnection,
            HashMap<String, FeeRates> feeRates,
            SyncStatus syncStatus) {
        this.mAccounts = accounts;
        this.mTransactions = transactions;
        this.mToken = token;
        this.mActiveUserId = activeUserId;
        this.mExchangeRates = exchangeRates;
        this.mTxServiceConnection = txServiceConnection;
        this.mFeeRates = feeRates;
        this.mSyncStatus = syncStatus;
    }

    public ArrayList<Account> getAccounts() {
        return mAccounts;
    }

    public ArrayList<Transaction> getTransactions() {
        return mTransactions;
    }

    public String getToken() {
        return mToken;
    }

    public String getActiveUserId() {
        return mActiveUserId;
    }

    public String getExchangeRates() {
        return mExchangeRates;
    }

    public TxServiceConnection getTxServiceConnection() {
        return mTxServiceConnection;
    }

    public HashMap<String, FeeRates> getFeeRates() {
        return mFeeRates;
    }

    public SyncStatus getSyncStatus() {
        return mSyncStatus;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof State)) {
            return false;
        }
        State other = (State) obj;
        return this.mAccounts.equals(other.mAccounts) &&
                this.mTransactions.equals(other.mTransactions) &&
                this.mToken.equals(other.mToken) &&
                ((this.mActiveUserId == null && other.mActiveUserId == null) || (this.mActiveUserId != null && this.mActiveUserId.equals(other.mActiveUserId))) &&
                this.mExchangeRates.equals(other.mExchangeRates) &&
                this.mTxServiceConnection.equals(other.mTxServiceConnection) &&
                this.mFeeRates.equals(other.mFeeRates) &&
                this.mSyncStatus == other.mSyncStatus;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mAccounts.hashCode();
        hashCode = hashCode * 31 + mTransactions.hashCode();
        hashCode = hashCode * 31 + mToken.hashCode();
        hashCode = hashCode * 31 + (mActiveUserId == null ? 0 : mActiveUserId.hashCode());
        hashCode = hashCode * 31 + mExchangeRates.hashCode();
        hashCode = hashCode * 31 + mTxServiceConnection.hashCode();
        hashCode = hashCode * 31 + mFeeRates.hashCode();
        hashCode = hashCode * 31 + mSyncStatus.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "State{" +
                "mAccounts=" + mAccounts +
                "," + "mTransactions=" + mTransactions +
                "," + "mToken=" + mToken +
                "," + "mActiveUserId=" + mActiveUserId +
                "," + "mExchangeRates=" + mExchangeRates +
                "," + "mTxServiceConnection=" + mTxServiceConnection +
                "," + "mFeeRates=" + mFeeRates +
                "," + "mSyncStatus=" + mSyncStatus +
        "}";
    }

}
