// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

/** Callback used by methods in {@link  User User} class..  */
public interface StringifiedJsonCallback {
    public void onError(Exception e);

    public void onSuccess(String stringifiedJson);
}
