// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in {@link  Wallet Wallet} class. */
public interface SubmitExchangeCallback {
    public void onError(Exception e);

    public void onSuccess(Exchange exchage);
}
