// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in @link user class. */
public interface SuccessCallback {
    public void onError(Exception e);

    public void onSuccess();
}
