// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Time intervals, such as 'hour', 'week' or 'year' */
public final class TimeInterval {

    public static final String HOUR = "hour";

    public static final String DAY = "day";

    public static final String WEEK = "week";

    public static final String MONTH = "month";

    public static final String QUARTER = "quarter";

    public static final String YEAR = "year";

    public static final String MAX = "max";


    public TimeInterval(
            ) {
    }

    @Override
    public String toString() {
        return "TimeInterval{" +
        "}";
    }

}
