// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Transaction direction, 'SENT' or 'RECEIVED'. */
public final class TransactionDirection {

    public static final String SENT = "SENT";

    public static final String RECEIVED = "RECEIVED";


    public TransactionDirection(
            ) {
    }

    @Override
    public String toString() {
        return "TransactionDirection{" +
        "}";
    }

}
