// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class TransactionStatus {

    public static final String PENDING = "PENDING";

    public static final String CONFIRMED = "CONFIRMED";

    public static final String FAILED = "FAILED";

    public static final String RESUBMITTED = "RESUBMITTED";

    public static final String CANCELLED = "CANCELLED";

    public static final String PAUSED = "PAUSED";


    public TransactionStatus(
            ) {
    }

    @Override
    public String toString() {
        return "TransactionStatus{" +
        "}";
    }

}
