// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class TransactionDirection {

    public static final String INCOMING = "INCOMING";

    public static final String OUTGOING = "OUTGOING";

    public static final String FAILED = "FAILED";

    public static final String RESUBMITTED = "RESUBMITTED";

    public static final String CANCELLED = "CANCELLED";

    public static final String PAUSED = "PAUSED";


    public TransactionDirection(
            ) {
    }

    @Override
    public String toString() {
        return "TransactionDirection{" +
        "}";
    }

}
