// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user.djinni

package money.zumo.zumokit;

import java.util.concurrent.atomic.AtomicBoolean;

/** Callback interface used by methods in @link user class. */
public interface TransactionListener {
    public void update(Transaction transaction);

    static final class CppProxy implements TransactionListener
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void update(Transaction transaction)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_update(this.nativeRef, transaction);
        }
        private native void native_update(long _nativeRef, Transaction transaction);
    }
}
