// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Transaction direction, 'INCOMING' or 'OUTGOING'. */
public final class TransactionDirection {

    public static final String INCOMING = "INCOMING";

    public static final String OUTGOING = "OUTGOING";


    public TransactionDirection(
            ) {
    }

    @Override
    public String toString() {
        return "TransactionDirection{" +
        "}";
    }

}
