// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enums.djinni

package money.zumo.zumokit;

/** Transaction type, 'CRYPTO', 'FIAT', 'NOMINATED' or 'CARD'. */
public final class TransactionType {

    public static final String CRYPTO = "CRYPTO";

    public static final String FIAT = "FIAT";

    public static final String NOMINATED = "NOMINATED";

    public static final String CARD = "CARD";


    public TransactionType(
            ) {
    }

    @Override
    public String toString() {
        return "TransactionType{" +
        "}";
    }

}
