// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public enum TransactionStatus {
    PENDING,
    CONFIRMED,
    FAILED,
    RESUBMITTED,
    CANCELLED,
    ;
}
