// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from state.djinni

package money.zumo.zumokit;

public final class TxServiceConnection {


    /*package*/ final ConnectionStatus mStatus;

    /*package*/ final long mLastConnected;

    public TxServiceConnection(
            ConnectionStatus status,
            long lastConnected) {
        this.mStatus = status;
        this.mLastConnected = lastConnected;
    }

    public ConnectionStatus getStatus() {
        return mStatus;
    }

    public long getLastConnected() {
        return mLastConnected;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof TxServiceConnection)) {
            return false;
        }
        TxServiceConnection other = (TxServiceConnection) obj;
        return this.mStatus == other.mStatus &&
                this.mLastConnected == other.mLastConnected;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mStatus.hashCode();
        hashCode = hashCode * 31 + ((int) (mLastConnected ^ (mLastConnected >>> 32)));
        return hashCode;
    }

    @Override
    public String toString() {
        return "TxServiceConnection{" +
                "mStatus=" + mStatus +
                "," + "mLastConnected=" + mLastConnected +
        "}";
    }

}
