// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from records.djinni

package money.zumo.zumokit;

public final class UnspentOutput {


    /*package*/ final String mTxHash;

    /*package*/ final int mTxOutputN;

    /*package*/ final long mValue;

    /*package*/ final String mScript;

    public UnspentOutput(
            String txHash,
            int txOutputN,
            long value,
            String script) {
        this.mTxHash = txHash;
        this.mTxOutputN = txOutputN;
        this.mValue = value;
        this.mScript = script;
    }

    public String getTxHash() {
        return mTxHash;
    }

    public int getTxOutputN() {
        return mTxOutputN;
    }

    public long getValue() {
        return mValue;
    }

    public String getScript() {
        return mScript;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof UnspentOutput)) {
            return false;
        }
        UnspentOutput other = (UnspentOutput) obj;
        return this.mTxHash.equals(other.mTxHash) &&
                this.mTxOutputN == other.mTxOutputN &&
                this.mValue == other.mValue &&
                this.mScript.equals(other.mScript);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mTxHash.hashCode();
        hashCode = hashCode * 31 + mTxOutputN;
        hashCode = hashCode * 31 + ((int) (mValue ^ (mValue >>> 32)));
        hashCode = hashCode * 31 + mScript.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "UnspentOutput{" +
                "mTxHash=" + mTxHash +
                "," + "mTxOutputN=" + mTxOutputN +
                "," + "mValue=" + mValue +
                "," + "mScript=" + mScript +
        "}";
    }

}
