// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

/** Callback interface used by methods in @link ZumoKit class */
public interface UserCallback {
    public void onError(Exception e);

    public void onSuccess(User user);
}
