// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

package money.zumo.zumokit;

import java.util.concurrent.atomic.AtomicBoolean;

public interface WebSocketListener {
    public void onOpen(String message);

    public void onMessage(String message);

    public void onClose(String message);

    public void onError(String message);

    static final class CppProxy implements WebSocketListener
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onOpen(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onOpen(this.nativeRef, message);
        }
        private native void native_onOpen(long _nativeRef, String message);

        @Override
        public void onMessage(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onMessage(this.nativeRef, message);
        }
        private native void native_onMessage(long _nativeRef, String message);

        @Override
        public void onClose(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onClose(this.nativeRef, message);
        }
        private native void native_onClose(long _nativeRef, String message);

        @Override
        public void onError(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onError(this.nativeRef, message);
        }
        private native void native_onError(long _nativeRef, String message);
    }
}
