// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from networking.djinni

package money.zumo.zumokit;

import java.util.concurrent.atomic.AtomicBoolean;

public interface WebSocketImpl {
    public void send(String message);

    public void subscribe(WebSocketListener listener);

    static final class CppProxy implements WebSocketImpl
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void send(String message)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_send(this.nativeRef, message);
        }
        private native void native_send(long _nativeRef, String message);

        @Override
        public void subscribe(WebSocketListener listener)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_subscribe(this.nativeRef, listener);
        }
        private native void native_subscribe(long _nativeRef, WebSocketListener listener);
    }
}
