// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package money.zumo.zumokit;

public final class ZumoKitErrorType {

    public static final String API_CONNECTION_ERROR = "api_connection_error";

    public static final String API_ERROR = "api_error";

    public static final String AUTHENTICATION_ERROR = "authentication_error";

    public static final String WALLET_ERROR = "wallet_error";

    public static final String INVALID_REQUEST_ERROR = "invalid_request_error";

    public static final String RATE_LIMIT_ERROR = "rate_limit_error";

    public static final String INVALID_ARGUMENT_ERROR = "invalid_argument_error";


    public ZumoKitErrorType(
            ) {
    }

    @Override
    public String toString() {
        return "ZumoKitErrorType{" +
        "}";
    }

}
