// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package money.zumo.zumokit;

public final class ZumoKitErrorCode {

    public static final String UNKNOWN_ERROR = "unknown_error";

    public static final String INVALID_API_RESPONSE = "invalid_api_response";

    public static final String INVALID_WEBSOCKET_RESPONSE = "invalid_websocket_response";

    public static final String API_SERVICE_ERROR = "api_service_error";

    public static final String TRANSACTION_SERVICE_ERROR = "transaction_service_error";

    public static final String NOT_AUTHORIZED = "not_authorized";

    public static final String WALLET_LIMIT_EXCEEDED = "wallet_limit_exceeded";

    public static final String NO_WALLET_TO_RECOVER_FOUND = "no_wallet_to_recover_found";

    public static final String INVALID_RECOVERY_PHRASE = "invalid_recovery_phrase";

    public static final String INVALID_MNEMONIC_WORD_COUNT = "invalid_mnemonic_word_count";

    public static final String INVALID_PASSWORD = "invalid_password";

    public static final String INVALID_NETWORK_TYPE = "invalid_network_type";

    public static final String BITCOIN_AMOUNT_OVERFLOW = "bitcoin_amount_overflow";

    public static final String SIGNING_ERROR = "signing_error";

    public static final String UTXO_SIGNING_ERROR = "utxo_signing_error";

    public static final String INVALID_HD_WALLET_PATH = "invalid_hd_wallet_path";

    public static final String CHANGE_ACCOUNT_NOT_FOUND = "change_account_not_found";

    public static final String ACCOUNT_NOT_FOUND = "account_not_found";

    public static final String KNOWN_TRANSACTION = "known_transaction";

    public static final String INVALID_TRANSACTION_VALUE = "invalid_transaction_value";

    public static final String INVALID_FEE_RATE = "invalid_fee_rate";

    public static final String INVALID_ADDRESS = "invalid_address";

    public static final String INSUFFICIENT_FUNDS = "insufficient_funds";

    public static final String INSUFFICIENT_FUNDS_FOR_TRANSACTION = "insufficient_funds_for_transaction";

    public static final String INSUFFICIENT_FUNDS_FOR_EXCHANGE = "insufficient_funds_for_exchange";

    public static final String NONCE_OVERFLOW = "nonce_overflow";

    public static final String GAS_TOO_LOW = "gas_too_low";

    public static final String GAS_OVERFLOW = "gas_overflow";

    public static final String NO_DESTINATION_ADDRESS = "no_destination_address";

    public static final String DATA_OVERFLOW = "data_overflow";

    public static final String INCOMPATIBLE_NETWORK_TYPES = "incompatible_network_types";

    public static final String INVALID_ACCOUNT_TYPE = "invalid_account_type";

    public static final String INVALID_EXCHANGE_RATE = "invalid_exchange_rate";

    public static final String INVALID_EXCHANGE_SETTINGS = "invalid_exchange_settings";

    public static final String EXCHANGE_RETURN_VALUE_NEGATIVE = "exchange_return_value_negative";

    public static final String INVALID_EXCHANGE_DEPOSIT_ADDRESS = "invalid_exchange_deposit_address";

    public static final String EXCHANGE_AMOUNT_TOO_LOW = "exchange_amount_too_low";

    public static final String VALUE_PROVIDED_WHEN_SEND_MAX_SET = "value_provided_when_send_max_set";

    public static final String DATA_PROVIDED_WHEN_SEND_MAX_SET = "data_provided_when_send_max_set";

    public static final String TRANSACTION_TOO_LARGE = "transaction_too_large";

    public static final String CHANGE_INDEX_OUT_OF_RANGE = "change_index_out_of_range";

    public static final String TRANSACTION_AMOUNT_TOO_SMALL = "transaction_amount_too_small";

    public static final String SEND_MAX_INSUFFICIENT_FUNDS_FOR_FEE = "send_max_insufficient_funds_for_fee";

    public static final String SEND_MAX_INSUFFICIENT_FUNDS_FOR_TRANSACTION = "send_max_insufficient_funds_for_transaction";

    public static final String AMOUNT_NOT_SET = "amount_not_set";

    public static final String ALREADY_MODULR_CUSTOMER = "already_modulr_customer";

    public static final String ACCOUNT_LIMIT_EXCEEDED = "account_limit_exceeded";

    public static final String DESTINATION_PROVIDED_WHEN_WITHDRAW_SET = "destination_provided_when_withdraw_set";

    public static final String INVALID_TRANSACTION_TYPE = "invalid_transaction_type";


    public ZumoKitErrorCode(
            ) {
    }

    @Override
    public String toString() {
        return "ZumoKitErrorCode{" +
        "}";
    }

}
