// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package money.zumo.zumokit;

public final class ZumoKitError {

    public static final String API_CONNECTION_ERROR = "api_connection_error";

    public static final String API_ERROR = "api_error";

    public static final String AUTHENTICATION_ERROR = "wallet_error";

    public static final String WALLET_ERROR = "wallet_error";

    public static final String TRANSACTION_ERROR = "transaction_error";

    public static final String INVALID_REQUEST_ERROR = "invalid_request_error";

    public static final String RATE_LIMIT_ERROR = "rate_limit_error";

    public static final String INVALID_ARGUMENT_ERROR = "invalid_argument_error";


    /*package*/ final String mType;

    /*package*/ final String mCode;

    /*package*/ final String mMessage;

    public ZumoKitError(
            String type,
            String code,
            String message) {
        this.mType = type;
        this.mCode = code;
        this.mMessage = message;
    }

    public String getType() {
        return mType;
    }

    public String getCode() {
        return mCode;
    }

    public String getMessage() {
        return mMessage;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof ZumoKitError)) {
            return false;
        }
        ZumoKitError other = (ZumoKitError) obj;
        return this.mType.equals(other.mType) &&
                ((this.mCode == null && other.mCode == null) || (this.mCode != null && this.mCode.equals(other.mCode))) &&
                ((this.mMessage == null && other.mMessage == null) || (this.mMessage != null && this.mMessage.equals(other.mMessage)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mType.hashCode();
        hashCode = hashCode * 31 + (mCode == null ? 0 : mCode.hashCode());
        hashCode = hashCode * 31 + (mMessage == null ? 0 : mMessage.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "ZumoKitError{" +
                "mType=" + mType +
                "," + "mCode=" + mCode +
                "," + "mMessage=" + mMessage +
        "}";
    }

}
