// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package money.zumo.zumokit;

public final class ZumoKitErrorCode {

    public static final String UNKNOWN_ERROR = "unknown_error";

    public static final String API_SERVICE_ERROR = "api_service_error";

    public static final String TRANSACTION_SERVICE_ERROR = "transaction_service_error";

    public static final String NOT_AUTHORIZED = "not_authorized";

    public static final String WALLET_LIMIT_EXCEEDED = "wallet_limit_exceeded";

    public static final String NO_WALLET_TO_RECOVER_FOUND = "no_wallet_to_recover_found";

    public static final String INVALID_RECOVERY_PHRASE = "invalid_recovery_phrase";

    public static final String INVALID_MNEMONIC_WORD_COUNT = "invalid_mnemonic_word_count";

    public static final String INVALID_PASSWORD = "invalid_password";

    public static final String INVALID_NETWORK_TYPE = "invalid_network_type";

    public static final String BITCOIN_AMOUNT_OVERFLOW = "bitcoin_amount_overflow";

    public static final String SIGNING_ERROR = "signing_error";

    public static final String UTXO_SIGNING_ERROR = "utxo_signing_error";

    public static final String INVALID_HD_WALLET_PATH = "invalid_hd_wallet_path";

    public static final String CHANGE_ACCOUNT_NOT_FOUND = "change_account_not_found";

    public static final String ACCOUNT_NOT_FOUND = "account_not_found";

    public static final String KNOWN_TRANSACTION = "known_transaction";

    public static final String INVALID_TRANSACTION_VALUE = "invalid_transaction_value";

    public static final String INVALID_FEE_RATE = "invalid_fee_rate";

    public static final String INVALID_ADDRESS = "invalid_address";

    public static final String INSUFFICIENT_FUNDS = "insufficient_funds";

    public static final String NONCE_OVERFLOW = "nonce_overflow";

    public static final String GAS_TOO_LOW = "gas_too_low";

    public static final String GAS_OVERFLOW = "gas_overflow";

    public static final String NO_DESTINATION_ADDRESS = "no_destination_address";

    public static final String DATA_OVERFLOW = "data_overflow";

    public static final String INCOMPATIBLE_NETWORK_TYPES = "incompatible_network_types";

    public static final String INVALID_ACCOUNT_TYPE = "invalid_account_type";

    public static final String INVALID_EXCHANGE_RATE = "invalid_exchange_rate";

    public static final String INVALID_EXCHANGE_FEES = "invalid_exchange_fees";

    public static final String EXCHANGE_RETURN_VALUE_NEGATIVE = "exchange_return_value_negative";


    public ZumoKitErrorCode(
            ) {
    }

    @Override
    public String toString() {
        return "ZumoKitErrorCode{" +
        "}";
    }

}
