// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from zumo_core.djinni

package money.zumo.zumokit;

import java.util.concurrent.atomic.AtomicBoolean;

/** Entry point to ZumoKit C++ SDK */
public interface ZumoCore {
    /**
     * Authenticates user token set and returns corresponding user. On success user is set as active user.
     * Refer to <a href="https://developers.zumo.money/docs/setup/server#get-zumokit-user-token">Server</a> guide for details on how to get user token set.
     *
     * @param userTokenSet   user token set
     * @param callback         an interface to receive the result or error
     *
     * @see User
     */
    public void authUser(String userTokenSet, UserCallback callback);

    /**
     * Get active user if exists.
     *
     * @return active user or null
     */
    public User getActiveUser();

    /**
     * Get crypto utils class.
     *
     * @return crypto utils
     */
    public Utils getUtils();

    /**
     * Get exchange rate for selected currency pair.
     *
     * @param fromCurrency   currency code
     * @param toCurrency     currency code
     *
     * @return exchange rate or null
     */
    public ExchangeRate getExchangeRate(String fromCurrency, String toCurrency);

    /**
     * Get exchange settings for selected currency pair.
     *
     * @param fromCurrency   currency code
     * @param toCurrency     currency code
     *
     * @return exchange settings or null
     */
    public ExchangeSettings getExchangeSettings(String fromCurrency, String toCurrency);

    /**
     * Get crypto currency fee rates for selected currency.
     *
     * @param currency   currency code
     *
     * @return exchange settings or null
     */
    public FeeRates getFeeRates(String currency);

    /**
     * Fetch historical exchange rates for supported time intervals.
     * On success callback returns historical exchange rates are contained in a mapping between
     * time interval on a top level, from currency on second level, to currency on third level and {@link  ExchangeRate ExchangeRate} objects.
     *
     * @param callback         an interface to receive the result or error
     *
     * @see HistoricalExchangeRatesInterval
     */
    public void fetchHistoricalExchangeRates(HistoricalExchangeRatesCallback callback);

    /**
     * Get ZumoKit SDK version.
     * @return semantic version tag if exists, commit hash otherwise
     */
    public static String getVersion()
    {
        return CppProxy.getVersion();
    }

    /**
     * Initializes ZumoKit SDK. Should only be called once.
     *
     * @param httpImpl        HTTP implementation
     * @param wsImpl          WebSocet implementation
     * @param apiKey          ZumoKit Api-Key
     * @param apiUrl         ZumoKit API url
     * @param txServiceUrl  ZumoKit Transaction Service url
     *
     * @return ZumoKit instance
     */
    public static ZumoCore init(HttpImpl httpImpl, WebSocketImpl wsImpl, String apiKey, String apiUrl, String txServiceUrl)
    {
        return CppProxy.init(httpImpl,
                             wsImpl,
                             apiKey,
                             apiUrl,
                             txServiceUrl);
    }

    static final class CppProxy implements ZumoCore
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void authUser(String userTokenSet, UserCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_authUser(this.nativeRef, userTokenSet, callback);
        }
        private native void native_authUser(long _nativeRef, String userTokenSet, UserCallback callback);

        @Override
        public User getActiveUser()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getActiveUser(this.nativeRef);
        }
        private native User native_getActiveUser(long _nativeRef);

        @Override
        public Utils getUtils()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getUtils(this.nativeRef);
        }
        private native Utils native_getUtils(long _nativeRef);

        @Override
        public ExchangeRate getExchangeRate(String fromCurrency, String toCurrency)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getExchangeRate(this.nativeRef, fromCurrency, toCurrency);
        }
        private native ExchangeRate native_getExchangeRate(long _nativeRef, String fromCurrency, String toCurrency);

        @Override
        public ExchangeSettings getExchangeSettings(String fromCurrency, String toCurrency)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getExchangeSettings(this.nativeRef, fromCurrency, toCurrency);
        }
        private native ExchangeSettings native_getExchangeSettings(long _nativeRef, String fromCurrency, String toCurrency);

        @Override
        public FeeRates getFeeRates(String currency)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getFeeRates(this.nativeRef, currency);
        }
        private native FeeRates native_getFeeRates(long _nativeRef, String currency);

        @Override
        public void fetchHistoricalExchangeRates(HistoricalExchangeRatesCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_fetchHistoricalExchangeRates(this.nativeRef, callback);
        }
        private native void native_fetchHistoricalExchangeRates(long _nativeRef, HistoricalExchangeRatesCallback callback);

        public static native String getVersion();

        public static native ZumoCore init(HttpImpl httpImpl, WebSocketImpl wsImpl, String apiKey, String apiUrl, String txServiceUrl);
    }
}
